name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install pv & bats
        run: sudo apt update && sudo apt install pv bats
      - name: add src to path
        run: echo "$(pwd)/src" >> $GITHUB_PATH
      - name: test
        run: |
          cd test
          bats *.bats
